# Generated by Django 5.1.4 on 2025-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('binance_withdraw_enable', models.BooleanField(default=False)),
                ('trading', models.BooleanField(default=False)),
                ('withdraw_enable', models.BooleanField(default=False)),
                ('x_effective_from', models.CharField(max_length=50)),
                ('x_effective_to', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'crypto',
                'constraints': [models.UniqueConstraint(fields=('id',), name='crypto_pk')],
            },
        ),
    ]
