# Generated by Django 5.1.4 on 2025-01-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('base_asset', models.CharField(max_length=20)),
                ('quote_asset', models.CharField(max_length=20)),
                ('x_effective_from', models.CharField(max_length=50)),
                ('x_effective_to', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'symbols',
                'constraints': [models.UniqueConstraint(fields=('id',), name='symbols_pk')],
            },
        ),
    ]
